package com.joshtalks.joshskills.core.abTest

enum class CampaignKeys(val NAME: String) {
    SPEAKING_INTRODUCTION_VIDEO("SPEAKING_INTRODUCTION_VIDEO"),
    ENGLISH_SYLLABUS_DOWNLOAD("ENGLISH_SYLLABUS_DOWNLOAD"),
    P2P_IMAGE_SHARING("P2P_IMAGE_SHARING")
}