package com.joshtalks.joshskills.core.abTest

enum class CampaignKeys(val NAME: String) {
    SPEAKING_INTRODUCTION_VIDEO("SPEAKING_INTRODUCTION_VIDEO"),
    ENGLISH_SYLLABUS_DOWNLOAD("ENGLISH_SYLLABUS_DOWNLOAD"),
    ACTIVITY_FEED("ACTIVITY_FEED"),
    P2P_IMAGE_SHARING("P2P_IMAGE_SHARING"),
    HUNDRED_POINTS("100_POINTS"),
    BUY_LAYOUT_CHANGED("BUY_LAYOUT_CHANGED"),
    WHATSAPP_REMARKETING("WHATSAPP_REMARKETING")
    PEOPLE_HELP_COUNT("PEOPLE_HELP_COUNT")
}