package com.joshtalks.joshskills.core.abTest

enum class GoalKeys(val NAME: String) {
    ESD_COURSE_BOUGHT("ESD_COURSE_BOUGHT"),
    SIV_GT_2MIN("SIV_GT_2MIN"),
    HUNDRED_POINTS_COURSE_BOUGHT("100P_COURSE_BOUGHT"),
    ACTIVITY_FEED_TS("AF_TS"),
    BLE_999_BOUGHT("BLE_999_BOUGHT"),
    P2P_IS_GT_20MIN("P2P_IS_GT_20MIN"),
    USER_FOR_WHATSAPP("USER_FOR_WHATSAPP")

}