package com.joshtalks.joshskills.core.abTest

enum class VariantKeys(val NAME: String) {
    SIV_ENABLED("SIV_ENABLED"),
    SIV_DISABLED("SIV_DISABLED"),
    POINTS_HUNDRED_ENABLED("100P_ENABLED"),
    POINTS_HUNDRED_DISABLED("100P_DISABLED"),
    SYLLABUS_ENABLED("SYLLABUS_ENABLED"),
    SYLLABUS_DISABLED("SYLLABUS_DISABLED"),
    P2P_IS_ENABLED("P2P_IS_ENABLED"),
    P2P_IS_DISABLED("P2P_IS_DISABLED")
}