package com.joshtalks.joshskills.core.abTest

enum class VariantKeys(val NAME: String) {
    SIV_ENABLED("SIV_ENABLED"),
    SIV_DISABLED("SIV_DISABLED"),
    POINTS_HUNDRED_ENABLED("100P_ENABLED"),
    POINTS_HUNDRED_DISABLED("100P_DISABLED"),
    ESD_ENABLED("ESD_ENABLED"),
    ESD_DISABLED("ESD_DISABLED"),
    P2P_IS_ENABLED("P2P_IS_ENABLED"),
    P2P_IS_DISABLED("P2P_IS_DISABLED"),
    ACTIVITY_FEED_ENABLED("AF_ENABLED"),
    ACTIVITY_FEED_DISABLED("AF_DISABLED"),
    BUY_LAYOUT_ENABLED("BUY_LAYOUT_ENABLED"),
    BUY_LAYOUT_DISABLED("BUY_LAYOUT_DISABLED"),
    EFT_ENABLED("EFT_ENABLED"),
    EFT_DISABLED("EFT_DISABLED")
}