package com.joshtalks.joshskills.ui.certification_exam.constants

const val CERTIFICATE_IMAGE_URL = "CERTIFICATE_IMAGE_URL"
const val CERTIFICATE_SHARE_FRAGMENT = "CERTIFICATE_SHARE_FRAGMENT"
const val CERTIFICATE_STACK = "CERTIFICATE_STACK"

const val REPORT_ID = "report_id"
const val COUNTRY_CODE = "+91"
const val CERTIFICATE_URL = "certificate_url"
const val LOCAL_DOWNLOAD_URL = "local_download_url"
const val CERTIFICATE_EXAM_ID = "certificateExamId"

const val PACKAGE_NAME_WHATSAPP = "com.whatsapp"
const val PACKAGE_NAME_FACEBOOK = "com.facebook.android"
const val PACKAGE_NAME_LINKEDIN = "com.linkedin.android"
const val PACKAGE_NAME_INSTA = "com.instagram.android"

const val CERTIFICATE_SHARED_WHATSAPP = "CERTIFICATE_SHARED_WHATSAPP"
const val CERTIFICATE_SHARED_FB = "CERTIFICATE_SHARED_FB"
const val CERTIFICATE_SHARED_INSTA = "CERTIFICATE_SHARED_INSTA"
const val CERTIFICATE_SHARED_LINKED = "CERTIFICATE_SHARED_LINKED"
const val CERTIFICATE_DOWNLOAD = "CERTIFICATE_DOWNLOAD"

const val OPENED_EXAM_INSTRUCTION_FRAGMENT  = "OPENED_EXAM_INSTRUCTION_FRAGMENT"
const val START_EXAM  = "START_EXAM"
const val PREV_RESULT  = "PREV_RESULT"
const val FINISH_EXAM  = "FINISH_EXAM"
const val GENERATE_CERTIFICATE_FORM  = "GENERATE_CERTIFICATE_FORM"
const val SHOW_CERTIFICATE  = "SHOW_CERTIFICATE"
const val GENERATE_CERTIFICATE  = "GENERATE_CERTIFICATE"
const val CHECK_EXAM_DETAILS  = "CHECK_EXAM_DETAILS"