package com.joshtalks.joshskills.ui.leaderboard.constants

const val HAS_SEEN_PROFILE_ANIMATION = "profile_pref_has_seen_profile_animation"
const val HAS_SEEN_LEADERBOARD_ITEM_ANIMATION = "leaderboard_pref_has_seen_leaderboard_item_animation"
const val HAS_SEEN_TODAYS_WINNER_ANIMATION = "leaderboard_pref_has_seen_todays_winner_animation"
const val HAS_SEEN_WEEKS_WINNER_ANIMATION = "leaderboard_pref_has_seen_weeks_winner_animation"
const val HAS_SEEN_LEADERBOARD_BATCH_ANIMATION = "leaderboard_pref_has_seen_batch_animation"
const val HAS_SEEN_LEADERBOARD_LIFETIME_ANIMATION = "leaderboard_pref_has_seen_lifetime_animation"
const val HAS_SEEN_MONTHS_WINNER_ANIMATION = "leaderboard_pref_has_seen_months_winner_animation"
const val HAS_SEEN_POINTS_HISTORY_ANIMATION = "points_pref_has_seen_point_history_animation"
const val HAS_SEEN_UNLOCK_CLASS_ANIMATION = "conversion_pref_has_seen_unlock_class_animation"
const val HAS_SEEN_GRAMMAR_ANIMATION = "grammar_pref_has_seen_grammar_button_animation"
const val HAS_SEEN_LEADERBOARD_TOOLTIP_1_ANIMATION = "conversion_pref_has_seen_leaderboard_tooltip_1_animation"
const val HAS_SEEN_LEADERBOARD_TOOLTIP_2_ANIMATION = "conversion_pref_has_seen_leaderboard_tooltip_2_animation"