package com.joshtalks.joshskills.core.analytics

enum class SingularEvent(override val value: String) : Event {

    APP_OPENED_FIRST_TIME("APP_OPENED_FIRST_TIME"),
    OPENED_PRE_CHECKOUT_PAGE("OPENED_PRE_CHECKOUT_PAGE"),
    OPENED_FREE_TRIAL_PAYMENT("OPENED_FREE_TRIAL_PAYMENT"),
    OPENED_CHECKOUT_PAGE("OPENED_CHECKOUT_PAGE"),
    INITIATED_PAYMENT("INITIATED_PAYMENT"),
    PAYMENT_SUCCESSFUL("PAYMENT_SUCCESSFUL"),
    PAYMENT_SUCCESS_EVENT("PAYMENT_SUCCESS_EVENT"),
    PAYMENT_FAILED("PAYMENT_FAILED")

}