package com.joshtalks.joshskills.constants

const val ON_BACK_PRESSED = 1
const val OPEN_GROUP = 2
const val SEARCH_GROUP = 3
const val CLEAR_SEARCH = 4
const val OPEN_POPUP_MENU = 5
const val OPEN_NEW_GROUP = 6
const val OPEN_IMAGE_CHOOSER = 7
const val GROUP_IMAGE_SELECTED = 8
const val ADD_GROUP_TO_SERVER = 9
const val OPEN_CALLING_ACTIVITY = 10
const val SHOULD_REFRESH_GROUP_LIST = 12
const val OPEN_GROUP_INFO = 13
const val EDIT_GROUP_INFO = 14
const val SAVE_GROUP_INFO = 15
const val OPEN_EMOJI_KEYBOARD = 16
const val CLEAR_CHAT_TEXT = 17
const val SEND_MSG = 18
const val INIT_LIST_TOOLTIP = 19
const val NEW_CHAT_ADDED = 20
const val REFRESH_GRP_LIST_HIDE_INFO = 21
const val REMOVE_GROUP_AND_CLOSE = 22
const val OPEN_PROFILE_PAGE = 23
const val SHOW_PROGRESS_BAR = 24
const val DISMISS_PROGRESS_BAR = 25
const val CREATE_GROUP_VALIDATION = 26
const val OPEN_ADMIN_RESPONSIBILITY = 27
const val OPEN_GROUP_REQUESTS_LIST = 28
const val OPEN_GROUP_REQUEST = 29
const val REQUEST_GROUP_VALIDATION = 30

const val COURSE_RESTART_SUCCESS = 78
const val COURSE_RESTART_FAILURE = 79

const val ON_BACK_PRESS = 100
const val INVITE_FRIENDS_METHOD = 101
const val PERMISSION_FROM_GRAMMAR = 102
const val PERMISSION_FROM_READING = 103
const val PERMISSION_FROM_READING_GRANTED = 104
const val SHARE_VIDEO = 105

const val ON_BACK_PRESS_PROFILE = 200
const val COURSE_LIST_DATA = 201
const val MY_GROUP_LIST_DATA = 202