package com.joshtalks.joshskills.premium.core.abTest

enum class VariantKeys(val NAME: String) {
    SIV_ENABLED("SIV_ENABLED"),
    POINTS_HUNDRED_ENABLED("100P_ENABLED"),
    WR_ENABLED("WR_ENABLED"),
    PHC_IS_ENABLED("PHC_IS_ENABLED"),
    EFT_ENABLED("EFT_ENABLED"),
    AF2_ENABLED("AF2_ENABLED"),
    TWENTY_MIN_ENABLED("20_MIN_ENABLED"),
    NEW_LANGUAGE_ENABLED("NEW_LANGUAGE_ENABLED"),
    A2_C1_RETENTION("A2_C1_RETENTION"),
    ICP_ENABLED("ICP_ENABLED"),
    ENGLISH_FOR_GOVT_EXAM_ENABLED("ENGLISH_FOR_GOVT_EXAM_ENABLED"),
    ORIGINAL_LOGIN_FLOW("ORIGINAL_LOGIN_FLOW"),
    NEW_LOGIN_AFTER_NAME("NEW_LOGIN_AFTER_NAME"),
    NEW_LOGIN_BEFORE_NAME("NEW_LOGIN_BEFORE_NAME"),
    L2_LESSON_COMPLETE_ENABLED("L2_LESSON_COMPLETE_ENABLED"),
    OTHER_SCREENS_BANNER_ENABLED("OTHER_SCREENS_BANNER_ENABLED"),
    SPEAKING_TOOLTIP_V2_ENABLED("SPEAKING_TOOLTIP_V2_ENABLED"),
    NEW_BUY_PAGE_V1_ENABLED("NEW_BUY_PAGE_V1_ENABLED"),
    NEW_BUY_PAGE_V2_ENABLED("NEW_BUY_PAGE_V2_ENABLED")
}
